name: Exemplo Artifact
run-name: Exemplo workflow para artifact, executa por ${{github.actor}}
on:
    workflow_dispatch:
env:
    nome-artefato: teste-artefato
jobs:
    upload_artifact:

        runs-on: ubuntu-latest
        steps:
            - name: Listagem de arquivs
              run: ls
            - name: Gerar alguns arquivos
              run: |
                mkdir artefatos
                echo "Arquivo de teste 01" > ./artefatos/primeiro_arquivo.txt
                echo "Arquivo de teste 02" > ./artefatos/segundo_arquivo.txt
                echo "Arquivo de teste 03" > ./artefatos/terceiro_arquivo.txt
                echo "Arquivo de teste 04" > ./artefatos/quarto_arquivo.txt
            - name: Envio dos arquivos
              uses: actions/upload-artifact@v4
              id: upload-artifact
              with: 
                name: ${{env.nome-artefato}}
                path: ./artefatos

            - name: Listagem de arquivo
              run: ls

            - name: Endereço para obtr os artefatos
              run: |
                echo "${{ steps.upload_artifact.outputs.artifact-url}}"
    download-artifact:
        runs-on: ubuntu-latest
        needs: [upload_artifact]
        steps:
            - name: Listagem de arquivos
              run: ls

            - name: Download Artifacts
              uses: actions/download-artifact@v4
              with:
                name: ${{env.nome-artefato}}
            
            - name: Listagem de arquivos
              run: ls